from sqlalchemy import Column, String, Integer, ForeignKey, Enum, DateTime, Float, Boolean, Text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship
from app.db import Base
import enum
import datetime
import uuid

class SectorEnum(str, enum.Enum):
    coal = "coal"
    steel = "steel"
    mica = "mica"

class RoleEnum(str, enum.Enum):
    admin = "admin"
    supervisor = "supervisor"
    worker = "worker"

class LanguageEnum(str, enum.Enum):
    en = "en"
    hi = "hi"
    sat = "sat"

class CertStatusEnum(str, enum.Enum):
    valid = "valid"
    revoked = "revoked"

class Organization(Base):
    __tablename__ = "organizations"
    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, nullable=False)
    sites = relationship("Site", back_populates="organization")

class Site(Base):
    __tablename__ = "sites"
    id = Column(Integer, primary_key=True, index=True)
    org_id = Column(Integer, ForeignKey("organizations.id"), nullable=False)
    code = Column(String, unique=True, index=True, nullable=False)
    name = Column(String, nullable=False)
    sector = Column(Enum(SectorEnum), nullable=False)
    district = Column(String)
    lat = Column(Float)
    lng = Column(Float)
    
    organization = relationship("Organization", back_populates="sites")
    users = relationship("User", back_populates="site")

class User(Base):
    __tablename__ = "users"
    id = Column(Integer, primary_key=True, index=True)
    site_id = Column(Integer, ForeignKey("sites.id"), nullable=True)
    role = Column(Enum(RoleEnum), nullable=False, default=RoleEnum.worker)
    worker_code = Column(String, unique=True, index=True)
    name = Column(String, nullable=False)
    phone = Column(String, unique=True, index=True)
    pin_hash = Column(String, nullable=False)
    language = Column(Enum(LanguageEnum), nullable=False, default=LanguageEnum.en)
    is_active = Column(Boolean, default=True)
    created_at = Column(DateTime, default=datetime.datetime.utcnow)

    site = relationship("Site", back_populates="users")

class Module(Base):
    __tablename__ = "modules"
    id = Column(Integer, primary_key=True, index=True)
    code = Column(String, unique=True, index=True, nullable=False)
    title_key = Column(String, nullable=False)
    version = Column(Integer, default=1)
    is_lite = Column(Boolean, default=False)
    validity_days = Column(Integer, default=365)
    pass_mark = Column(Integer, default=70)

class Attempt(Base):
    __tablename__ = "attempts"
    id = Column(String, primary_key=True) # UUID string generated by client
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    module_code = Column(String, ForeignKey("modules.code"), nullable=False)
    started_at = Column(DateTime, nullable=False)
    submitted_at = Column(DateTime, nullable=False)
    device_id = Column(String)
    client_score = Column(Float)
    server_score = Column(Float)
    ar_score = Column(Float)
    assess_score = Column(Float)
    passed = Column(Boolean)
    app_version = Column(String)

class AttemptAnswer(Base):
    __tablename__ = "attempt_answers"
    id = Column(Integer, primary_key=True, index=True)
    attempt_id = Column(String, ForeignKey("attempts.id"), nullable=False)
    question_id = Column(String, nullable=False)
    answer_json = Column(Text)
    time_ms = Column(Integer)
    is_correct = Column(Boolean)

class AttemptStep(Base):
    __tablename__ = "attempt_steps"
    id = Column(Integer, primary_key=True, index=True)
    attempt_id = Column(String, ForeignKey("attempts.id"), nullable=False)
    step_id = Column(String, nullable=False)
    points = Column(Integer)
    max_points = Column(Integer)
    attempts = Column(Integer)
    duration_ms = Column(Integer)
    mistakes_json = Column(Text)

class Certificate(Base):
    __tablename__ = "certificates"
    id = Column(String, primary_key=True) # UUID
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    module_code = Column(String, ForeignKey("modules.code"), nullable=False)
    attempt_id = Column(String, ForeignKey("attempts.id"), nullable=False)
    score = Column(Float)
    issued_at = Column(DateTime, nullable=False)
    expires_at = Column(DateTime, nullable=False)
    status = Column(Enum(CertStatusEnum), default=CertStatusEnum.valid)
    payload_json = Column(Text)
    signature_b64 = Column(String)
    revoked_reason = Column(String)
    revoked_at = Column(DateTime)

class MicroQuizResult(Base):
    __tablename__ = "micro_quiz_results"
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    module_code = Column(String, ForeignKey("modules.code"), nullable=False)
    day_offset = Column(Integer)
    score = Column(Float)
    taken_at = Column(DateTime)

class AuditLog(Base):
    __tablename__ = "audit_log"
    id = Column(Integer, primary_key=True, index=True)
    actor_id = Column(Integer, ForeignKey("users.id"), nullable=True)
    action = Column(String, nullable=False)
    entity = Column(String)
    entity_id = Column(String)
    at = Column(DateTime, default=datetime.datetime.utcnow)
    meta_json = Column(Text)

class ContentVersion(Base):
    __tablename__ = "content_versions"
    id = Column(Integer, primary_key=True, index=True)
    version = Column(Integer, nullable=False)
    created_at = Column(DateTime, default=datetime.datetime.utcnow)
